---
# Anastasia Kondratieva <anastasia@asiaknt.com>
# enero 2024

AWSTemplateFormatVersion: 2010-09-09

Description: >-
  This AWS CloudFormation template creates a given number of EC2 instances 
  with access from the internet

Parameters:
  NumberOfInstances:
    Type: String
    Description: 'Numero de instancias a desplegar. Cuidado, puede incurrir en gastos'
    Default: '1'   
  AMIId:
    Type: String
    Description: 'AMI de las instancias' 
  IDTag:
    Type: String
    Description: 'Etiqueta que identifica a las instancias del grupo'

Resources:

  #############################################################################
  # Security group granting access to the instances via SSH                   #
  #############################################################################
  Ec2SecurityGroup: 
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      VpcId: 'vpc-083e28986645f5eb3'
      GroupDescription: 'Enable SSH access to Bastion via port 22'
      # SecurityGroupIngress:
      #   IpProtocol: tcp
      #   FromPort: '22'
      #   ToPort: '22'
      #   CidrIp: '0.0.0.0/0'
      #   Description: 'SSH Access to the instance from everywhere'
      Tags: 
      - Key: 'Name'
        Value: !Join [ '-', [ 'CCAPost', 'ec2', !Ref 'IDTag', 'sg' ] ]

  # #############################################################################
  # # Launch configuration for the ASG                                          #
  # #############################################################################
  LaunchConfiguration:
    Type: 'AWS::AutoScaling::LaunchConfiguration'
    Properties:
      ImageId: !Ref 'AMIId'
      InstanceType: 't2.micro'
      SecurityGroups:
        - !Ref 'Ec2SecurityGroup'
      KeyName: 'postgrado'
      AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: !Sub |  
          #!/bin/bash
          yum update -y                          
          yum update
          yum install -y docker
          usermod -a -G docker ec2-user
          systemctl enable docker.service
          systemctl start docker.service

  # #############################################################################
  # # Auto Scaling Group                                                        #
  # #############################################################################
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: [ 'subnet-033ab11aefc4719d5' ]
      LaunchConfigurationName: !Ref 'LaunchConfiguration'
      MinSize: !Ref 'NumberOfInstances'
      MaxSize: !Ref 'NumberOfInstances'
      DesiredCapacity: !Ref 'NumberOfInstances'
      Tags:
        - Key: Name
          Value: !Join [ '-', [ 'CCAPost', !Ref 'IDTag', 'ec2' ] ]
          PropagateAtLaunch: true
