---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: k8s.rael.io/greeting-operator-source:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/k8s_v1_greeting_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the k8s.rael.io/v1.Greeting
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/k8s_v1_greeting_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='k8s.rael.io', api_version='v1', kind='Greeting', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 60s for reconciliation to run
    k8s_facts:
      api_version: 'v1'
      kind: 'Greeting'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 6
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
